version: '3.8'

services: 

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: solar_watch
    ports:
      - "29777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      retries: 5
      timeout: 5s

  solarwatch:
    image: solarwatch:latest
    build:
      context: ./SolarWatch/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING_DOCKER=Server=postgres;Port=5432;Database=solar_watch;User Id=admin;Password=123456
    ports:
      - "5000:5000"
    depends_on:
        postgres:
          condition: service_healthy

  frontend:
    build:
      context: ./SolarWatch_Frontend/
      dockerfile: Dockerfile
    container_name: solarwatch_frontend
    environment:
      - VITE_API_BASE_URL=http://solarwatch:5000
    ports:
      - "3000:80"
    depends_on:
      - solarwatch

volumes:
  postgres_data:
